### ISSUE TITLE
Magic panic on Decode()

### ISSUE THREAD

**Issue by monopollly** [dvsekhvalnov/jose2go#11] opened 2016-05-04 11:29 UTC
I don't understand the magic panic on Decode()
I have 2 jwt keys with equals structure:

**The First key is OK** (decode without panic error):

`eyJhbGciOiJIUzI1NiIsImV4cGlyZSI6MTQ2Mjk2MzczNiwidHlwIjoiSldUIn0.eyJpZCI6MSwicHJvdmlkZXIiOiJlbWFpbCIsImFjY2VzcyI6bnVsbH0.d9RmVg-_ZApjodPiBUXxuS7qRrO0dc5i7cMj1THWln0`

**But second one** ("expire date" header is changed only) **make Panic**:

`eyJhbGciOiJIUzI1NiIsImV4cGlyZSI6MTQ2Mjk1OTM1NiwidHlwIjoiSldUIn0.eyJpZCI6MSwicHJvdmlkZXIiOiJlbWFpbCIsImFjY2VzcyI6bnVsbH0.ktTgHtd_jXUIP3LprcxPjYpZAn9HhyiQviOjmuwiHVI.eyJpZCI6MSwicHJvdmlkZXIiOiJlbWFpbCIsImFjY2VzcyI6bnVsbH0.xKoTn8vaWy2VcP7pGx42ynImFPt64L1tgbZknDz8-ek`

it looks like:

```
panic: interface conversion: interface is nil, not string
Stack trace:
goroutine 34 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/dvsekhvalnov/jose2go.decrypt(0xc82017a700, 0x5, 0x5, 0x414100, 0xc820172b20, 0x0, 0x0, 0x107, 0x0, 0x0)
	/Volumes/future.go/src/github.com/dvsekhvalnov/jose2go/jose.go:330 +0x3ec
github.com/dvsekhvalnov/jose2go.Decode(0xc82019cfc0, 0x107, 0x414100, 0xc820172b20, 0x0, 0x0, 0xc8201981e0, 0x0, 0x0)
	/Volumes/future.go/src/github.com/dvsekhvalnov/jose2go/jose.go:252 +0x185
main.(*Token).parse(0xc8201981e0, 0xc82019cc60, 0x107, 0x120, 0xc820157768)
```

Please help me to understand this magic!
I check both keys here [https://jwt.io](https://jwt.io) all is valid

I try to handle the error but all point to Decode() function

My decode block looks like this:
`data, headers, err := jose.Decode(string(token), jwtSecretKey)`

Nobody loves panic errors and I have to understand the problem.
Thank you for any help!

**Comment by dvsekhvalnov** [comment] 2016-05-04 12:35
Hi @monopollly,

can you please post minimal test case here? (e.g. code that i can run to check issue)

Thank you.

**Comment by dvsekhvalnov** [comment] 2016-05-04 12:49
Sounds like duplicate of https://github.com/dvsekhvalnov/jose2go/issues/10 at the first glance.

**Comment by dvsekhvalnov** [comment] 2016-05-04 13:11
Hey, @monopollly , you second token actually invalid. It says signing alg in header: HS256, but contains five parts as encrypted one.  

I agree that panic is not good and better to return meaningful error. Will fix as i have time (or i'm accepting patch requests :)

**Comment by monopollly** [comment] 2016-05-04 15:41
All tokens created and parse by this functions:

```
var jwtSecretKey = []byte("magic")

type Token struct{
    Days           time.Duration       `json:"-"`    
    ID               int                         `json:"id"`
    Provider      string                    `json:"provider"`
    Access        []string                  `json:"access"`  
}

func (t *Token) create() []byte {
        t.Days = 7
        mm, _ := json.Marshal(t)
        data := string(mm)
        expired := time.Now().Add(time.Hour * 24 * t.Days).Unix()
	token, err := jose.Sign(data, jose.HS256, jwtSecretKey, jose.Header("expire", expired))
        if err == nil {
            return []byte(token)
        }
        return nil
}

func (t *Token) parse(token []byte) bool {
	data, headers, err := jose.Decode(string(token), jwtSecretKey)
    if err != nil {
        //Token parse error
        return false
    }
    time64 := int64(headers["expire"].(float64))
    if  time64 < time.Now().Unix() {
        //Token is outdate
        return false
    }
    err = json.Unmarshal([]byte(data), t)
    if err != nil {
        return false
    }
    return true
}
```

can't format code here(
but something like that

**Comment by dvsekhvalnov** [comment] 2016-05-04 15:54
@monopollly see my comments below. 

You first token - is signed token, your second - is invalid encrypted one (missing required `enc` header, wrong 'alg' header value).

BTW why do you convert string tokens to []byte and back, library operates on strings?

**Comment by dvsekhvalnov** [comment] 2016-05-06 07:41
@monopollly i fixed panic issue. So try again and let me know if it's get better.

**Closed by dvsekhvalnov** 2016-05-06 07:41 UTC
Labels: bug, duplicate

**Comment by monopollly** [comment] 2016-05-07 10:55
@dvsekhvalnov  Awesome! thanks. now its more better!)

> 1. why do you convert string tokens to []byte and back, library operates on strings?

   you mean this `jose.Decode(string(token)...`?
because I just get a token in []byte from server
how I can decode []byte token instead string?

> 2. your jwtSecretKey is of invalid length (too short). for HS256 it should be 256bits (384 bits for HS384, e.t.c.) . jose2go doesn't enforce min length, but probably should.

ok, i'll know, thanks!
